### ISSUE TITLE
Bug: Account id changes when importing mnemonic words to Seed from Mintter.

### ISSUE THREAD

**Issue by SalvaZaraes** [seed-hypermedia/seed#32]
## Problem

Just installed Seed Hypermedia, inputed the 12 words that originally backed my Mintter account and the account id has changed.
Therefore, I expect that my articles won't appear in the Seed account.

**Comment by burdiyan** [comment]
It's true, we changed the format of Account IDs between Mintter and Seed, because we needed to fix some of the things in our key derivation procedure. In fact, Seed has no backward compatibility with Mintter. There is (or is about to be released) an export/import feature, such that you could export your documents from Mintter and import them into Seed.

**Comment by SalvaZaraes** [comment]
Great! Thanks for your response.
